# Gym 1 - Basics

## PyTorch basics

Ref https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -4.6566e-10,  0.0000e+00],
        [-4.6566e-10,  4.2039e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.0752e-05,  1.7280e-04],
        [ 1.6800e-07,  3.3459e+21,  4.2316e+21]])


In [3]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.2335])
1.2335470914840698


### Autograd
Ref https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

In [65]:
import torch

In [66]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [67]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [68]:
print(y.grad_fn)

In [69]:
out = y.mean()
out

tensor(3., grad_fn=<MeanBackward1>)

In [93]:
out.backward()
out

tensor(3., grad_fn=<MeanBackward1>)

In [95]:
x.grad

tensor([[2.5000, 2.5000],
        [2.5000, 2.5000]])

Generally speaking, torch.autograd is an engine for computing vector-[Jacobian](https://en.wikipedia.org/wiki/Jacobian_matrix_and_determinant) product. 

In [96]:
x = torch.randn(3, requires_grad=True)

y = x * 2

In [104]:
import math

3.0290886163603994

In [106]:
y.data.norm()

tensor(3.0291)