<a href="https://colab.research.google.com/github/gromag/Gym-NeuralNetwork/blob/master/Gym%2010%20-%20Tensorflow/Coursera_Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Notebook for testing layers shapes

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Flatten, Softmax, BatchNormalization, Conv1D, Dropout, MaxPooling2D, Input, AveragePooling1D

In [15]:
inputs = Input(shape=(32,1))
h = Conv1D(3, 5, activation='relu', name="conv1d_layer")(inputs)
h = AveragePooling1D(3)(h)
h = Flatten(name='flatten')(h)
outputs = Dense(1, activation='sigmoid')(h)

model = Model(inputs=inputs, outputs=outputs)

model.layers[1].weights

[<tf.Variable 'conv1d_layer/kernel:0' shape=(5, 1, 3) dtype=float32, numpy=
 array([[[ 0.1245926 , -0.43398225,  0.41630805]],
 
        [[ 0.04097176,  0.33567816, -0.1110152 ]],
 
        [[ 0.0618794 ,  0.01969767,  0.52203083]],
 
        [[ 0.25143892,  0.0427053 ,  0.01003146]],
 
        [[ 0.37227094,  0.01502538, -0.08766073]]], dtype=float32)>,
 <tf.Variable 'conv1d_layer/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [7]:
model.layers[1].get_weights()

[array([[[-0.4609501 , -0.28568465,  0.26282746]],
 
        [[-0.40010193, -0.30966938,  0.1757614 ]],
 
        [[ 0.48283017, -0.0257799 ,  0.1681    ]],
 
        [[ 0.09975755, -0.07096177,  0.40127122]],
 
        [[-0.5072687 , -0.31586534, -0.4361777 ]]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [8]:
model.layers[1].kernel

<tf.Variable 'conv1d_layer/kernel:0' shape=(5, 1, 3) dtype=float32, numpy=
array([[[-0.4609501 , -0.28568465,  0.26282746]],

       [[-0.40010193, -0.30966938,  0.1757614 ]],

       [[ 0.48283017, -0.0257799 ,  0.1681    ]],

       [[ 0.09975755, -0.07096177,  0.40127122]],

       [[-0.5072687 , -0.31586534, -0.4361777 ]]], dtype=float32)>

In [9]:
model.layers[1].bias

<tf.Variable 'conv1d_layer/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [11]:
model.get_layer('conv1d_layer').weights

[<tf.Variable 'conv1d_layer/kernel:0' shape=(5, 1, 3) dtype=float32, numpy=
 array([[[-0.4609501 , -0.28568465,  0.26282746]],
 
        [[-0.40010193, -0.30966938,  0.1757614 ]],
 
        [[ 0.48283017, -0.0257799 ,  0.1681    ]],
 
        [[ 0.09975755, -0.07096177,  0.40127122]],
 
        [[-0.5072687 , -0.31586534, -0.4361777 ]]], dtype=float32)>,
 <tf.Variable 'conv1d_layer/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [13]:
model.layers[1].input

<KerasTensor: shape=(None, 32, 1) dtype=float32 (created by layer 'input_2')>

In [14]:
model.layers[1].output

<KerasTensor: shape=(None, 28, 3) dtype=float32 (created by layer 'conv1d_layer')>

In [19]:
flatten_outputs = model.get_layer('flatten').output

model2 = Model(inputs = inputs, outputs = flatten_outputs)

In [20]:
model3 = Sequential([
                     model2,
                     Dense(10, activation='softmax', name='new_dense_layer')
])

In [22]:
new_output = Dense(10, activation='softmax', name='new_dense_layer')(model2.output)
model4 = Model(inputs=model2.input, outputs = new_output)